spring:
  application:
    name: IdentityService
  datasource:
    url: "jdbc:postgresql://localhost:5432/test"
    username: postgres
    password: 123
  jpa: 
    hibernate: 
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  servlet:
    context-path: /identity
  error: 
    include-message: always

jwt:
  singerKey: "erBbQWxtozTCcuxiDMgfAlp0xI22EoEGRVhLZMt3N9WTCbbYpPPfYDOstWVUSEqN"

